# Generated by Django 5.2.4 on 2025-07-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ATMRegisterBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('card_number', models.CharField(max_length=100)),
                ('request_type', models.CharField(max_length=100)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('fingerprint', models.ImageField(blank=True, null=True, upload_to='fingerprints/')),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerComplaintBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('complaint_details', models.TextField()),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('fingerprint', models.ImageField(blank=True, null=True, upload_to='fingerprints/')),
                ('resolution', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomerVisitorBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(blank=True, max_length=100, null=True)),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('purpose', models.TextField()),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('fingerprint', models.ImageField(blank=True, null=True, upload_to='fingerprints/')),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='InternalTransferBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('from_account', models.CharField(max_length=100)),
                ('to_account', models.CharField(max_length=100)),
                ('transfer_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transfer_date', models.DateTimeField(auto_now_add=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('fingerprint', models.ImageField(blank=True, null=True, upload_to='fingerprints/')),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StatementRegisterBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255)),
                ('account_number', models.CharField(max_length=100)),
                ('statement_period', models.CharField(max_length=100)),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('signature', models.ImageField(blank=True, null=True, upload_to='signatures/')),
                ('fingerprint', models.ImageField(blank=True, null=True, upload_to='fingerprints/')),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
