# Generated by Django 5.2.4 on 2025-07-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmregisterbook',
            name='customer_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
