# Generated by Django 5.2.4 on 2025-07-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0002_atmregisterbook_customer_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmregisterbook',
            name='customer_photo',
            field=models.ImageField(blank=True, null=True, upload_to='customer_photos/'),
        ),
    ]
