# Generated by Django 5.2.4 on 2025-07-31 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0003_atmregisterbook_customer_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atmregisterbook',
            old_name='customer_photo',
            new_name='photo',
        ),
    ]
