# Generated by Django 5.2.4 on 2025-07-31 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0004_rename_customer_photo_atmregisterbook_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='atmregisterbook',
            old_name='photo',
            new_name='customer_photo',
        ),
    ]
