# Generated by Django 5.2.4 on 2025-07-31 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0005_rename_photo_atmregisterbook_customer_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atmregisterbook',
            name='customer_photo',
        ),
        migrations.AlterField(
            model_name='atmregisterbook',
            name='fingerprint',
            field=models.ImageField(blank=True, null=True, upload_to='fingerprints/', verbose_name='Customer Photo'),
        ),
    ]
