# Generated by Django 5.2.4 on 2025-07-31 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0006_remove_atmregisterbook_customer_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmregisterbook',
            name='fingerprint',
            field=models.ImageField(blank=True, null=True, upload_to='fingerprints/'),
        ),
    ]
