# Generated by Django 5.2.4 on 2025-07-31 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0007_alter_atmregisterbook_fingerprint'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atmregisterbook',
            options={'ordering': ['-request_date'], 'verbose_name': 'ATM Registration', 'verbose_name_plural': 'ATM Registrations'},
        ),
        migrations.AlterField(
            model_name='atmregisterbook',
            name='fingerprint',
            field=models.ImageField(blank=True, help_text='Upload customer photo (supported formats: JPG, JPEG, PNG)', null=True, upload_to='fingerprints/customer_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])], verbose_name='Customer Photo'),
        ),
    ]
