# Generated by Django 5.2.4 on 2025-07-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0008_alter_atmregisterbook_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmregisterbook',
            name='fingerprint',
            field=models.ImageField(blank=True, db_column='CUSTOMER PHOTO', null=True, upload_to='fingerprints/'),
        ),
    ]
