# Generated by Django 5.2.4 on 2025-07-31 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0009_alter_atmregisterbook_fingerprint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atmregisterbook',
            name='fingerprint',
            field=models.ImageField(blank=True, null=True, upload_to='fingerprints/', verbose_name='Customer Photo'),
        ),
    ]
