# Generated by Django 5.2.4 on 2025-08-03 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0010_alter_atmregisterbook_fingerprint'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmregisterbook',
            name='status',
            field=models.CharField(choices=[('Taken', 'Taken ✓'), ('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Taken', max_length=20),
        ),
    ]
