# Generated by Django 5.2.4 on 2025-08-03 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cooperative', '0011_atmregisterbook_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='atmregisterbook',
            name='dispatched_by',
            field=models.CharField(blank=True, help_text='Officer who dispatched the card', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='atmregisterbook',
            name='officer_signature',
            field=models.ImageField(blank=True, null=True, upload_to='officer_signatures/', verbose_name='Officer Signature'),
        ),
    ]
